name: clean_architecture_template
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.5.0
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
